package org.ajikhoji.passwordmanager.config;

import org.ajikhoji.passwordmanager.model.LabelEntity;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DbHandler {

    private final static String STR_DATABASE_URL_ONE = System.getenv("DATABASE_URL_ONE");
    private final static String STR_DATABASE_URL_TWO = System.getenv("DATABASE_URL_TWO");
    private final static String STR_DATABASE_NAME = System.getenv("DATABASE_NAME");
    private final static String STR_USER_NAME = System.getenv("DATABASE_USERNAME");
    private final static String STR_PASSWORD = System.getenv("DATABASE_PASSWORD");
    private final static String STR_DATABASE_PATH = System.getenv("LOCALAPPDATA") + System.getenv("DATABASE_PATH");
    private static DbHandler handler;

    private Connection con = null;

    private DbHandler() {
        if(STR_DATABASE_NAME == null || STR_USER_NAME == null || STR_PASSWORD == null || STR_DATABASE_PATH.equals(System.getenv("LOCALAPPDATA"))) {
            System.err.println("Unable to load Data as a problem persists on Database configuration");
            System.exit(-1);
            return;
        }
        if(!new File(String.format("%s\\%s.log", STR_DATABASE_PATH, STR_DATABASE_NAME)).exists()) {
            this.configureDatabase();
        }
        this.init();
    }

    public static DbHandler getInstance() {
        if(handler == null) {
            handler = new DbHandler();
        }
        return handler;
    }

    private void configureDatabase() {
        //open the database and create a new USER with password GRANTING ALL access.
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            final String jdbcUrl = String.format(STR_DATABASE_URL_ONE, STR_DATABASE_PATH, STR_DATABASE_NAME);
            this.con = DriverManager.getConnection(jdbcUrl, "SA", "");

            this.con.setAutoCommit(false);
            final Statement stmt = this.con.createStatement();
            stmt.executeUpdate(String.format(
                    "CREATE USER \"%s\" PASSWORD '%s' ADMIN;",
                    STR_USER_NAME, STR_PASSWORD
            ));
            stmt.executeUpdate(String.format(
                    "GRANT DBA TO \"%s\";",
                    STR_USER_NAME
            ));
            this.con.commit();
            this.con.close();
            this.con = null;
        } catch (final ClassNotFoundException | SQLException e) {
            System.err.println(DbHandler.class.getCanonicalName() + " - configureDatabase(): Error in opening database.");
            e.printStackTrace();
        }

        //deleting default user to restrict access through it.
        final String jdbcUrl = String.format(STR_DATABASE_URL_TWO, STR_DATABASE_PATH, STR_DATABASE_NAME);
        try (final Connection conn = DriverManager.getConnection(jdbcUrl, STR_USER_NAME, STR_PASSWORD);
             final Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("DROP USER SA;");
            conn.commit();
        } catch (SQLException e) {
            System.err.println(DbHandler.class.getCanonicalName() + " - configureDatabase(): Error in opening database.");
            e.printStackTrace();
        }
    }

    private void executeQuery(final String query) {
        try {
            final Statement st = this.con.createStatement();
            st.execute(query);
        } catch (final Exception e) {
            e.printStackTrace(System.err);
        }
    }

    private void init() {
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            final String jdbcUrl = String.format(STR_DATABASE_URL_TWO, STR_DATABASE_PATH, STR_DATABASE_NAME);
            this.con = DriverManager.getConnection(jdbcUrl, STR_USER_NAME, STR_PASSWORD);
        } catch (final ClassNotFoundException | SQLException e) {
            System.err.println(DbHandler.class.getCanonicalName() + " - Constructor: Error in opening database.");
            e.printStackTrace();
        }

        final String queryCreateLabelTable =
                """
                CREATE TABLE IF NOT EXISTS Labels (
                    label_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    label_name VARCHAR(20)
                );
                """;
        this.executeQuery(queryCreateLabelTable);

        final String queryAddDefaultLabelValue =
                String.format(
                    """
                    MERGE INTO Labels l
                    USING (VALUES ('%s')) AS vals(label_name)
                    ON l.label_name = vals.label_name
                    WHEN NOT MATCHED THEN
                        INSERT (label_name) VALUES (vals.label_name);
                    """
                , LabelEntity.DEFAULT_LABEL_NAME);
        this.executeQuery(queryAddDefaultLabelValue);

        final String queryCreateAccountsTable =
                """
                CREATE TABLE IF NOT EXISTS Accounts (
                    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_name VARCHAR(90) NOT NULL,
                    password VARCHAR(512) NOT NULL,
                    platform VARCHAR(90) NOT NULL,
                    label_id BIGINT,
                    link VARCHAR(300),
                    usage_count INTEGER DEFAULT 0,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP,
                    last_used_at TIMESTAMP
                );
                """;
        this.executeQuery(queryCreateAccountsTable);

        final String queryCreateAccountsCustomFieldsTable =
                """
                CREATE TABLE IF NOT EXISTS AccountCustomFields (
                    account_id BIGINT NOT NULL,
                    field_key VARCHAR(512) NOT NULL,
                    field_value VARCHAR(512) NOT NULL,
                
                    PRIMARY KEY (account_id, field_key),
                
                    FOREIGN KEY (account_id)
                        REFERENCES Accounts(account_id)
                        ON DELETE CASCADE
                );
                """;
        this.executeQuery(queryCreateAccountsCustomFieldsTable);

        final String queryCreateAppSettingsRelation =
                """
                CREATE TABLE IF NOT EXISTS AppSettings (
                    setting_key VARCHAR(33) PRIMARY KEY,
                    setting_value VARCHAR(255) NOT NULL
                );
                """;
        this.executeQuery(queryCreateAppSettingsRelation);
    }

    public Connection getConnection() {
        return this.con;
    }

    public void closeConnection() {
        try {
            if (this.con == null || this.con.isClosed()) {
                return;
            }
            this.con.close();
        } catch (Exception e) {
            System.err.println("Failed to close the database connection");
            e.printStackTrace(System.err);
        }
    }

}
